# -*- coding: utf-8 -*-
"""Ex1-Fasore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oNZI1lGio5Wgb5ThCkfFOv6PYxCbXpcQ
"""

import numpy as np # Importa la libreria NumPy per operazioni numeriche e array
import matplotlib.pyplot as plt # Importa Matplotlib per la creazione di grafici
import matplotlib.animation as animation # Importa il modulo animation per creare animazioni
from IPython.display import HTML, display # Importa HTML e display per mostrare l'animazione in Colab

plt.close('all') # Chiude tutte le figure Matplotlib precedentemente aperte per iniziare con una tela pulita

# Parametri del cerchio
raggio = 1 # Definisce il raggio del cerchio unitario

# Configurazione del grafico
fig = plt.figure(figsize=(8, 8)) # Crea una nuova figura con dimensioni 8x8 pollici
# Grafico principale per l'animazione del cerchio
ax = fig.add_axes([0.1, 0.4, 0.8, 0.55]) # Aggiunge un asse al grafico principale [sinistra, in basso, larghezza, altezza]
ax.set_aspect('equal', adjustable='box') # Imposta l'aspetto degli assi in modo che le unità siano uguali (cerchio non deformato)
ax.set_xlim(-raggio - 1, raggio + 1) # Imposta i limiti dell'asse X
ax.set_ylim(-raggio - 1, raggio + 1) # Imposta i limiti dell'asse Y
ax.grid(True) # Abilita la griglia sul grafico
ax.set_title('Punto sulla circonferenza e proiezioni su assi X e Y') # Imposta il titolo del grafico principale

# Disegna il cerchio
circle = plt.Circle((0, 0), raggio, color='blue', fill=False) # Crea un oggetto cerchio con centro (0,0), raggio e colore blu (non riempito)
ax.add_patch(circle) # Aggiunge il cerchio al grafico principale

# Inizializza gli oggetti da animare
point, = ax.plot([], [], 'o', color='red', markersize=8, label='Punto sulla circonferenza') # Inizializza il punto sulla circonferenza (marker rosso)
proj_x_line, = ax.plot([], [], '--', color='orange', alpha=0.7, label='Proiezione X') # Inizializza la linea di proiezione sull'asse X (arancione tratteggiata)
proj_y_line, = ax.plot([], [], '--', color='green', alpha=0.7, label='Proiezione Y') # Inizializza la linea di proiezione sull'asse Y (verde tratteggiata)
proj_x_point, = ax.plot([], [], 'o', color='orange', markersize=6) # Inizializza il punto di proiezione sull'asse X (marker arancione)
proj_y_point, = ax.plot([], [], 'o', color='green', markersize=6) # Inizializza il punto di proiezione sull'asse Y (marker verde)

# Linee degli assi per le proiezioni (sempre visibili)
ax.axhline(0, color='black', linewidth=0.5) # Disegna una linea orizzontale all'altezza y=0 (asse X)
ax.axvline(0, color='black', linewidth=0.5) # Disegna una linea verticale all'altezza x=0 (asse Y)

# Aggiungi le curve di seno e coseno (opzionale ma utile per visualizzare)
t_vals_full = np.linspace(0, 2 * np.pi, 200) # Genera valori per l'angolo theta da 0 a 2*pi per le curve complete (non usati direttamente nell'animazione, ma utili per contesto)
# Posizione del grafico sin/cosin, più in basso del grafico del cerchio
ax_sin_cos = fig.add_axes([0.1, 0.05, 0.8, 0.2]) # Aggiunge un secondo asse per i grafici di seno e coseno [sinistra, in basso, larghezza, altezza]
ax_sin_cos.set_xlim(0, 2 * np.pi) # Imposta i limiti dell'asse X per seno/coseno (da 0 a 2*pi)
ax_sin_cos.set_ylim(-1.1, 1.1) # Imposta i limiti dell'asse Y per seno/coseno
ax_sin_cos.grid(True) # Abilita la griglia sul grafico seno/coseno
ax_sin_cos.set_title('sin(theta) e cos(theta)') # Imposta il titolo del grafico seno/coseno

line_cos, = ax_sin_cos.plot([], [], label='cos(theta)', color='orange') # Inizializza la linea per il coseno
line_sin, = ax_sin_cos.plot([], [], label='sin(theta)', color='green') # Inizializza la linea per il seno

ax.legend() # Mostra la legenda sul grafico principale

# ---------- inizio funzioni
def init(): # Funzione di inizializzazione per l'animazione
    point.set_data([], []) # Resetta i dati del punto sulla circonferenza
    proj_x_line.set_data([], []) # Resetta i dati della linea di proiezione X
    proj_y_line.set_data([], []) # Resetta i dati della linea di proiezione Y
    proj_x_point.set_data([], []) # Resetta i dati del punto di proiezione X
    proj_y_point.set_data([], []) # Resetta i dati del punto di proiezione Y
    line_cos.set_data([], []) # Resetta i dati della curva del coseno
    line_sin.set_data([], []) # Resetta i dati della curva del seno
    return point, proj_x_line, proj_y_line, proj_x_point, proj_y_point, line_cos, line_sin # Restituisce tutti gli oggetti che verranno aggiornati

def update(frame): # Funzione di aggiornamento per ogni frame dell'animazione
    # Angolo in radianti
    theta = 2 * np.pi * frame / 100 # Calcola l'angolo theta in base al frame corrente (0-99)

    # Coordinate del punto sulla circonferenza
    x = raggio * np.cos(theta) # Calcola la coordinata x del punto sulla circonferenza
    y = raggio * np.sin(theta) # Calcola la coordinata y del punto sulla circonferenza

    point.set_data([x], [y]) # Aggiorna la posizione del punto sulla circonferenza

    # Proiezione sull'asse X
    proj_x_line.set_data([x, x], [0, y]) # Aggiorna la linea di proiezione X (dal punto all'asse X)
    proj_x_point.set_data([x], [0]) # Aggiorna la posizione del punto di proiezione sull'asse X

    # Proiezione sull'asse Y
    proj_y_line.set_data([0, x], [y, y]) # Aggiorna la linea di proiezione Y (dal punto all'asse Y)
    proj_y_point.set_data([0], [y]) # Aggiorna la posizione del punto di proiezione sull'asse Y

    # Aggiorna i grafici di seno e coseno
    t_vals = np.linspace(0, theta, 50) # Genera valori per l'angolo da 0 all'angolo corrente theta
    line_cos.set_data(t_vals, np.cos(t_vals)) # Aggiorna la curva del coseno fino all'angolo corrente
    line_sin.set_data(t_vals, np.sin(t_vals)) # Aggiorna la curva del seno fino all'angolo corrente

    return point, proj_x_line, proj_y_line, proj_x_point, proj_y_point, line_cos, line_sin # Restituisce gli oggetti aggiornati
# ---------- fine funzioni

# Creazione dell'animazione
ani = animation.FuncAnimation(fig, update, frames=range(100), init_func=init,
                              blit=True, interval=50, repeat=False) # Crea l'oggetto animazione

# Mostra l'animazione in Colab in modo controllato
animation_html = ani.to_jshtml() # Genera la stringa HTML che contiene l'animazione

plt.close(fig) # Chiude immediatamente la figura Matplotlib per evitare che venga renderizzata staticamente

display(HTML(animation_html)) # Visualizza esplicitamente l'animazione HTML nell'output di Colab

